<?php

/**
 * @file
 * wysiwyg_codemagic is a plugin for the TinyMCE Wysiwyg editor
 */

function _wysiwyg_codemagic_default_path() {
  return function_exists('wysiwyg_get_path')
      ? wysiwyg_get_path('tinymce') . '/jscripts/tiny_mce/plugins/codemagic'
      : 'sites/all/libraries/tinymce/jscripts/tiny_mce/plugins/codemagic';
}

/**
 * Implements hook_help().
 */
function wysiwyg_codemagic_help($path, $arg) {
  if ($path == 'admin/modules#description') {
    return t('Enables the TinyMCE CodeMagic plugin');
  }
}

/**
 * Implements hook_wysiwyg_plugin().
 */

function wysiwyg_codemagic_wysiwyg_plugin($editor) {
  switch ($editor) {
    case 'tinymce':
      $path = variable_get('wysiwyg_codemagic_tinymce_codemagic_location', _wysiwyg_codemagic_default_path());
      if (file_exists("$path/editor_plugin.js")) {
        return array(
          'codemagic' => array(
            'path' => $path,
            'filename' => 'editor_plugin.js',
            'buttons' => array('codemagic' => t('CodeMagic')),
            'url' => 'http://drupal.org/project/wysiwyg_codemagic/',
            'internal' => FALSE, 
	    'load' => TRUE,
          ),
        );
      }
  }
}
